services:
  mysql:
    image: mysql:9.0
    # NOTE: Change these credentials for a production deployment!
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qds-network
  
  # The Backend API (FastAPI)
  backend:
    profiles:
      - disabled
    build: .
    command: uvicorn src.quick_ds.apps.api.main:app --host 0.0.0.0 --port 5086
    volumes:
      - .:/app
    ports:
      - "5086:5086"

  # The Frontend (Reflex or Streamlit)
  frontend:
    profiles:
      - disabled
    build: .
    command: streamlit run src/apps/ui/app.py
    ports:
      - "8501:8501"
    depends_on:
      - api

  # ZenML Local Dashboard (Optional service for visibility)
  zenml-ui:
    image: zenmldocker/zenml-server
    ports:
      - "8080:8080"
    environment:
      - ZENML_SERVER_AUTO_ACTIVATE=1
      - ZENML_DEFAULT_USER_NAME=admin
      - ZENML_DEFAULT_USER_PASSWORD=${ZENML_DEFAULT_USER_PASSWORD}
      - ZENML_STORE_URL=${ZENML_STORE_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - qds-network

  langflow:
    profiles:
      - langflow  # enable with `--profile langflow` on docker-compose command line
    image: langflowai/langflow:latest  # or another version tag on https://hub.docker.com/r/langflowai/langflow
    restart: unless-stopped
    pull_policy: always  # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - qds-backend
    environment:
      - LANGFLOW_DATABASE_URL=${QDS_DATABASE_URL}
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY}
      - LANGFLOW_SKIP_AUTH_AUTO_LOGIN=${LANGFLOW_SKIP_AUTH_AUTO_LOGIN}
      - LANGFLOW_SUPERUSER=${LANGFLOW_SUPERUSER}
      - LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD}
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
    volumes:
      - ./data/langflow:/app/langflow
    networks:
      - qds-network

networks:
  qds-network:
    driver: bridge