# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# pipeline configuration
test_size: 0.35
drop_na: false
normalize: false
drop_columns: null
target: "target"
random_state: 17
dataset_path: null
output_path: null
