# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# pipeline configuration
parameters:
  test_size: 0.35
  drop_na: False
  normalize: False
  drop_columns: null
  targets: [SAND_FLAG, PORD]
  random_state: 17
  dataset_path: data\01_raw\raw_data.csv
  output_path: data\02_intermediate