# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# configuration of the Model Control Plane
model:
  name: sand_classifier
  version: sgdc
  license: Apache 2.0
  description: A sand flag classifier
  tags: ["sand_flag", "classifier"]

# Configure the pipeline
parameters:
  targets: [SAND_FLAG]
  model_type: "sgdc"
  dataset_path: data\01_raw\raw_data.csv
  score_thold: 0.7